### PR TITLE
Made package stack compatible

### PR DESCRIPTION
**Pull request by ScottSedgwick**
Created and added stack.yaml and .gitignore files.
Relaxed the version dependency on 'binary' package in cabal file.  Is that OK?
Also brought the minimum cabal version to >=1.8, so I could add a test target that pulls in the library.
Changed all tabs to spaces - I don't know when the Haskell compiler started giving warnings about that.

### CODE REVIEW

**Comment by dmwit** [comment]
Hm. I'd rather not pollute the edit history with whitespace changes if we can avoid it. Let's just put `-fno-warn-tabs` in the appropriate `ghc-options` fields in the cabal file instead.

I'm okay with relaxing the constraint on `binary`, but deleting it entirely is moving backwards. (Ideally all the other packages would have stricter bounds, too, if I only had the time...) If it builds with 0.8.* and 0.9, let's make it <0.10.

**Comment by dmwit** [comment]
For what it's worth, it does appear to build with binary-0.8 and -0.9. I'm currently checking what the appropriate bounds should be for the other packages, then I'll push a commit with those changes.

I'll also grab your `stack.yaml` in a future commit.

Then I'll comment here again to ask you to check whether I've got all the important changes, or whether more is needed to work with stack.

**Comment by dmwit** [comment]
I think I grabbed all the relevant changes from your commit. Confirm/deny? I'll make a release as soon as I hear from you.

**Comment by ScottSedgwick** [comment]
Hi Daniel,

Sorry I haven't been getting back to you - my email has been too eager in
binning your emails.

I agree with all your changes, and thanks for your help.


Scott.

**Comment by dmwit** [comment]
No worries, I wasn't expecting immediate replies anyway -- just wanted to
keep you up to date. =)

Ideally I'll take a look tomorrow evening at making a release.

~d

**Comment by ScottSedgwick** [comment]
Thanks Daniel.

**Pull request merged**
